/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoomCodeRouteImport } from './routes/_authenticated/room.$code'
import { Route as AuthenticatedPlaySoloRouteImport } from './routes/_authenticated/play.solo'
import { Route as AuthenticatedPlayJoinRouteImport } from './routes/_authenticated/play.join'
import { Route as AuthenticatedPlayCreateRouteImport } from './routes/_authenticated/play.create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomCodeRoute = AuthenticatedRoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaySoloRoute = AuthenticatedPlaySoloRouteImport.update({
  id: '/play/solo',
  path: '/play/solo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayJoinRoute = AuthenticatedPlayJoinRouteImport.update({
  id: '/play/join',
  path: '/play/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayCreateRoute = AuthenticatedPlayCreateRouteImport.update({
  id: '/play/create',
  path: '/play/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/play/create': typeof AuthenticatedPlayCreateRoute
  '/play/join': typeof AuthenticatedPlayJoinRoute
  '/play/solo': typeof AuthenticatedPlaySoloRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/play/create': typeof AuthenticatedPlayCreateRoute
  '/play/join': typeof AuthenticatedPlayJoinRoute
  '/play/solo': typeof AuthenticatedPlaySoloRoute
  '/room/$code': typeof AuthenticatedRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/play/create': typeof AuthenticatedPlayCreateRoute
  '/_authenticated/play/join': typeof AuthenticatedPlayJoinRoute
  '/_authenticated/play/solo': typeof AuthenticatedPlaySoloRoute
  '/_authenticated/room/$code': typeof AuthenticatedRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/play/create'
    | '/play/join'
    | '/play/solo'
    | '/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/play/create'
    | '/play/join'
    | '/play/solo'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/play/create'
    | '/_authenticated/play/join'
    | '/_authenticated/play/solo'
    | '/_authenticated/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room/$code': {
      id: '/_authenticated/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof AuthenticatedRoomCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/solo': {
      id: '/_authenticated/play/solo'
      path: '/play/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof AuthenticatedPlaySoloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/join': {
      id: '/_authenticated/play/join'
      path: '/play/join'
      fullPath: '/play/join'
      preLoaderRoute: typeof AuthenticatedPlayJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/create': {
      id: '/_authenticated/play/create'
      path: '/play/create'
      fullPath: '/play/create'
      preLoaderRoute: typeof AuthenticatedPlayCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPlayCreateRoute: typeof AuthenticatedPlayCreateRoute
  AuthenticatedPlayJoinRoute: typeof AuthenticatedPlayJoinRoute
  AuthenticatedPlaySoloRoute: typeof AuthenticatedPlaySoloRoute
  AuthenticatedRoomCodeRoute: typeof AuthenticatedRoomCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPlayCreateRoute: AuthenticatedPlayCreateRoute,
  AuthenticatedPlayJoinRoute: AuthenticatedPlayJoinRoute,
  AuthenticatedPlaySoloRoute: AuthenticatedPlaySoloRoute,
  AuthenticatedRoomCodeRoute: AuthenticatedRoomCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
